name: Workflow

on:
  push:
    branches: [master]
    paths:
      - src/**
      - public/**
  pull_request:
    branches: [master]
    paths:
      - src/**
      - public/**

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install and build
        run: |
          yarn install --frozen-lockfile
          yarn build

      # - name: Test
      #   run: yarn test:unit

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
